<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="config" nsURI="http://config/1.0" nsPrefix="config">
  <eClassifiers xsi:type="ecore:EClass" name="ModelElementOverride">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MinimumCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="StringPools" upperBound="-1"
        eType="#//StringPool" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="References" upperBound="-1"
        eType="#//ReferenceOverride" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelConfiguration">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ModelElementOverrides"
        upperBound="-1" eType="#//ModelElementOverride" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="TotalMinimumCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ModelElemetExclusions"
        upperBound="-1" eType="#//ModelElementExclusion" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Deterministic" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DefaultStringPool" eType="#//StringPool"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Generator" eType="#//Generator"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElementExclusion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringPool" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FileStringPool" eSuperTypes="#//StringPool">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EmbeddedStringPool" eSuperTypes="#//StringPool">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Strings" lowerBound="1"
        upperBound="-1" eType="#//StringPoolEntry"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Entries" lowerBound="1"
        upperBound="-1" eType="#//StringPoolEntry" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringPoolEntry">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="string" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReferenceOverride">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MinimumCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="MaximumCount" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Generator" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="strategy" lowerBound="1"
        eType="#//Strategy" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RandomGenerator" eSuperTypes="#//Generator"/>
  <eClassifiers xsi:type="ecore:EClass" name="Strategy" abstract="true" interface="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlwaysCreateStrategy" eSuperTypes="#//Strategy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="generator" lowerBound="1"
        eType="#//Generator"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AlwaysRetrieveStrategy" eSuperTypes="#//Strategy"/>
  <eClassifiers xsi:type="ecore:EClass" name="AlwaysRetrieveOrCreateStrategy" eSuperTypes="#//Strategy">
    <eStructuralFeatures xsi:type="ecore:EReference" name="retriver" lowerBound="1"
        eType="#//AlwaysRetrieveStrategy" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="creator" lowerBound="1"
        eType="#//AlwaysCreateStrategy" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EolGenerator" eSuperTypes="#//Generator">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CombinedGenerator" eSuperTypes="#//Generator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fallback" lowerBound="1"
        eType="#//Generator" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generators" upperBound="-1"
        eType="#//Generator" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
